export type SecurityGuideCategory = "API security" | "Web security" | "Identity and access" | "Testing workflow";

export type SecurityGuideSection = {
  title: string;
  paragraphs: string[];
  checklist?: string[];
  source?: number;
};

export type SecurityGuide = {
  slug: string;
  title: string;
  description: string;
  category: SecurityGuideCategory;
  answer: string;
  updated: string;
  sections: SecurityGuideSection[];
  limitations: string;
  faqs: { question: string; answer: string }[];
  sources: { title: string; url: string }[];
  related: string[];
};

const UPDATED = "2026-10-02";
const cheatSheet = (name: string) => `https://cheatsheetseries.owasp.org/cheatsheets/${name}_Cheat_Sheet.html`;

/** Editorial guides. Each route answers a different assessment question. */
export const SECURITY_GUIDES: SecurityGuide[] = [
  {
    slug: "bola-testing",
    title: "BOLA testing: verify object ownership in APIs",
    description: "Learn how to assess broken object level authorization with two test accounts, ownership controls, and evidence that distinguishes a real access failure.",
    category: "API security",
    answer: "Broken object level authorization (BOLA) happens when an API lets a caller access or change an object they are not entitled to use. Test the permission decision for the object and action, using records created by separate authorized test accounts.",
    updated: UPDATED,
    sections: [
      { title: "Start with an ownership model", paragraphs: ["For an invoice API, decide who may read an invoice, download its attachment, or change its status. A random identifier can make a record harder to guess, but the server still needs to enforce the permission rule when that identifier arrives."], source: 0 },
      { title: "Create a paired account check", paragraphs: ["Create one invoice for account A and a different invoice for account B. Record a normal request from each. With permission to test both accounts, check whether A's session can reach B's test record and compare the result against the intended policy."], checklist: ["Use harmless records whose owner and contents you know.", "Cover read, update, download, and nested resource routes separately.", "Check that shared records remain accessible to their intended collaborators."] },
      { title: "Prove the permission failure", paragraphs: ["A successful HTTP status is insufficient. A response might contain an empty result, a generic page, or A's own data. Evidence should connect the authenticated caller, the specific test object, its owner, the forbidden action, and the data returned or state changed."], checklist: ["Redact session tokens and customer data from saved requests.", "Record the expected denial as well as the observed response.", "Use an allowed same-owner request as a control."] },
      { title: "Retest every route to the object", paragraphs: ["A fix on the main invoice route can leave the PDF export or a batch route exposed. Add regression cases for the same ownership boundary through each access path. Preserve a positive case so the fix does not block a user from their own invoices."] },
    ],
    limitations: "Without separate accounts, known record ownership, and an agreed sharing policy, a scanner can identify candidate routes but cannot establish the full authorization boundary. Destructive actions need a disposable fixture and explicit scope.",
    faqs: [
      { question: "Are BOLA and IDOR the same thing?", answer: "IDOR describes an insecure direct reference to an object. BOLA emphasizes the missing permission decision around an API object. The terminology overlaps, so reports should explain the actual caller, object, and unauthorized action." },
      { question: "Do UUIDs prevent BOLA?", answer: "No. Knowing or receiving an object identifier must not give a caller permission to use the object. Unpredictable IDs complement access checks but do not replace them." },
      { question: "Does a 200 response prove BOLA?", answer: "No. Verify the response contains the other test account's protected record or that the forbidden state change occurred. Status codes alone do not establish impact." },
    ],
    sources: [{ title: "OWASP API1:2023 Broken Object Level Authorization", url: "https://api-security.owasp.org/editions/2023/en/0xa1-broken-object-level-authorization/" }],
    related: ["access-control-testing", "saas-tenant-isolation", "security-testing-report"],
  },
  {
    slug: "access-control-testing",
    title: "Access control testing with a role and action matrix",
    description: "Build a practical access control assessment across user roles, objects, and actions, including denied requests and valid permissions.",
    category: "Identity and access",
    answer: "Access control testing checks whether the server applies the application's permission rules to each protected action. Begin with a matrix of roles, resources, and operations, then test both allowed and forbidden combinations through the underlying API.",
    updated: UPDATED,
    sections: [
      { title: "Write the policy before the test", paragraphs: ["Authentication establishes who the caller is; authorization decides what that caller may do. Document the intended permissions for roles such as viewer, editor, administrator, and service account. Include object ownership and tenant membership where the same role has different rights over different data."], source: 0 },
      { title: "Test the server behind the interface", paragraphs: ["A hidden settings button tells you how the interface behaves, but says little about the endpoint. In a test workspace, send the corresponding request as a role that should be denied. Keep the administrator's valid request as a comparison."], checklist: ["List actions separately: read, create, update, export, and delete.", "Include direct routes, bulk operations, and alternate HTTP methods.", "Use a low privilege test account for every restricted feature."] },
      { title: "Exercise role transitions", paragraphs: ["Permissions change when a user leaves a workspace, loses an administrator role, or accepts an invitation. A session issued before that change may still exist. Check what happens to subsequent actions using that session, and agree whether the product requires immediate revocation or a documented delay."], checklist: ["Check a removed member against the old workspace's test record.", "Confirm the remaining administrator still has legitimate access.", "Record the session age and role change time in the evidence."] },
      { title: "Turn the matrix into regression coverage", paragraphs: ["Store allowed and denied cases beside the feature tests. When a new export endpoint appears, add its permission row before release. A compact, maintained matrix is more useful than a large checklist that assumes every application has the same roles."], source: 1 },
    ],
    limitations: "The tester cannot decide intended access rights from response behavior alone. Ambiguous sharing, support access, and delegated service permissions require product-owner input. One denied route does not establish that every route applies the policy.",
    faqs: [
      { question: "Is hiding an admin page an access control fix?", answer: "The protected operation needs a server-side permission check. Hiding the page may improve the interface, but direct API calls must enforce the same policy." },
      { question: "Should denied requests always return 403?", answer: "Some applications use 404 to avoid revealing a protected resource. The assessment should verify that data and state are protected, then document the chosen error behavior." },
      { question: "What is a useful access control test fixture?", answer: "Use a small workspace with separate roles, known records, and a written sharing policy. This lets you identify the exact permission failure without touching unrelated customer data." },
    ],
    sources: [{ title: "OWASP Authorization Cheat Sheet", url: cheatSheet("Authorization") }, { title: "OWASP Authorization Testing Automation Cheat Sheet", url: cheatSheet("Authorization_Testing_Automation") }],
    related: ["bola-testing", "authentication-security-testing", "remediation-retesting"],
  },
  {
    slug: "xss-testing",
    title: "XSS testing: trace untrusted input to browser output",
    description: "Understand reflected, stored, and DOM XSS assessment, browser evidence, output contexts, and why a reflected string is not proof of execution.",
    category: "Web security",
    answer: "Cross-site scripting (XSS) occurs when untrusted content is interpreted as active browser code in an application. A useful assessment traces the input to its output context and verifies browser behavior with harmless test data in an authorized environment.",
    updated: UPDATED,
    sections: [
      { title: "Identify the output context", paragraphs: ["Text in an HTML body, an attribute, a URL, and a script are different output contexts. Framework escaping helps with ordinary rendering, while raw HTML insertion and unsafe DOM operations deserve separate review. The correct protection depends on where the value is used."], source: 0 },
      { title: "Follow a harmless marker", paragraphs: ["Use a distinct text marker to follow a search term, profile field, or support message from entry to display. For stored content, inspect both the submitting user's view and any staff or collaborator view that renders the same record."], checklist: ["Record the page and exact element where the marker appears.", "Inspect the rendered DOM as well as the network response.", "Include preview, notification, and administrative views in scope."] },
      { title: "Separate reflection from execution", paragraphs: ["Finding a marker in a response establishes a data path, not an XSS vulnerability. Review how the browser parses it and whether escaping or sanitization keeps it inert. Any active confirmation should use an agreed harmless effect and stop at the smallest evidence necessary."], checklist: ["Keep session tokens and personal information out of the demonstration.", "Compare a normal value against the candidate unsafe context.", "Record whether a policy blocks the action and which protection applies."] },
      { title: "Fix the rendering path", paragraphs: ["Prefer safe rendering operations and context-appropriate encoding. When rich HTML is required, use a maintained sanitizer with a deliberate allowed format. Retest the affected view and another legitimate rich-content example so the repair preserves intended formatting."], source: 0 },
    ],
    limitations: "An HTTP-only scan can miss client-side DOM behavior and views that require another role. Content Security Policy may reduce impact without repairing the rendering defect. A text reflection or a suspicious HTML fragment alone is not confirmed XSS.",
    faqs: [
      { question: "What distinguishes stored and reflected XSS?", answer: "Stored input is saved and rendered later, potentially to another user. Reflected input returns in the response to the current request. Both require an unsafe browser interpretation to establish XSS." },
      { question: "Can a modern frontend framework still have XSS?", answer: "Yes. Raw HTML features, unsafe URL handling, third-party widgets, and direct DOM operations can create paths outside ordinary framework escaping." },
      { question: "Is a WAF sufficient remediation for XSS?", answer: "Fix the unsafe rendering or sanitization path. A filtering layer may block some requests but does not establish that all browser output contexts handle untrusted content safely." },
    ],
    sources: [{ title: "OWASP Cross Site Scripting Prevention Cheat Sheet", url: cheatSheet("Cross_Site_Scripting_Prevention") }],
    related: ["content-security-policy", "file-upload-security", "remediation-retesting"],
  },
  {
    slug: "sql-injection-testing",
    title: "SQL injection testing and evidence quality",
    description: "Assess SQL injection candidates using query review, stable controls, and safe evidence, without confusing database errors with confirmed injection.",
    category: "Web security",
    answer: "SQL injection happens when untrusted input changes the structure or meaning of a database query. Assessment should connect a controllable input to query construction or reproducible query behavior, rather than treating a database error as proof.",
    updated: UPDATED,
    sections: [
      { title: "Review the data and query boundary", paragraphs: ["Parameterized queries separate bound data from SQL structure. Review query-building code around search, filtering, sorting, and reporting. Dynamic table or column choices require deliberate allowed values because they are not ordinary data parameters."], source: 0 },
      { title: "Choose a bounded assessment path", paragraphs: ["A staging search endpoint with seeded records is a better place to investigate a candidate than a production checkout. Record normal responses and latency before introducing controlled variations. Agree on a request budget and avoid tests that modify or extract unrelated data."], checklist: ["Use fixtures with a known expected result set.", "Identify the parameter and route independently of the error message.", "Obtain separate approval for expensive or state-changing checks."] },
      { title: "Rule out ordinary failures", paragraphs: ["A malformed request can trigger validation, caching, a gateway timeout, or a database exception without changing query semantics. Repeat the control and candidate conditions under similar load. If only timing suggests a problem, retain the variability and alternative explanations in the report."], checklist: ["Record response differences across several controlled comparisons.", "Check whether the same error occurs with unrelated invalid input.", "Use code review or application logs when safely available."] },
      { title: "Repair and retest the affected query", paragraphs: ["Replace unsafe concatenation with the database library's parameter binding. Retest the original candidate and the intended search or filter behavior. Review adjacent query builders because a shared helper can repeat the defect across several endpoints."], source: 0 },
    ],
    limitations: "A generic SQL error is a candidate signal. Timing evidence is particularly sensitive to network and server noise. Tests must respect data and availability limits; destructive queries and large data extraction are unnecessary for most remediation decisions.",
    faqs: [
      { question: "Does input validation alone prevent SQL injection?", answer: "Validation helps enforce business rules, but query construction still needs safe parameter binding. Fields that legitimately accept punctuation must remain data rather than becoming query syntax." },
      { question: "Does every database exception indicate injection?", answer: "No. An exception may reveal error handling or validation problems. Establish how the input affects the query before labeling the finding SQL injection." },
      { question: "Can an ORM introduce SQL injection?", answer: "An ORM does not make raw SQL fragments safe automatically. Review escape hatches, string-built conditions, and dynamic sorting alongside ordinary ORM queries." },
    ],
    sources: [{ title: "OWASP SQL Injection Prevention Cheat Sheet", url: cheatSheet("SQL_Injection_Prevention") }],
    related: ["security-testing-report", "remediation-retesting", "automated-vs-manual-testing"],
  },
  {
    slug: "ssrf-testing",
    title: "SSRF testing for URL fetching features",
    description: "Review URL importers, webhooks, and preview features for server-side request forgery using controlled destinations and clear network boundaries.",
    category: "API security",
    answer: "Server-side request forgery (SSRF) happens when a caller can make a server send an unintended network request. Start with features that fetch URLs, then establish which destinations the server should be allowed to reach and verify that boundary with controlled test endpoints.",
    updated: UPDATED,
    sections: [
      { title: "Map server-side URL fetchers", paragraphs: ["Link previews, document importers, image proxies, and webhook delivery can all make outbound requests. Identify whether the product needs a fixed destination set or arbitrary public destinations. That decision changes how application validation and network restrictions should work."], source: 0 },
      { title: "Use endpoints you control", paragraphs: ["An authorized test receiver can log a unique marker and show that a server made a request. Give each assessment run a distinct marker and record the feature invocation time. Keep the receiver free of customer data and avoid requesting cloud metadata or internal services unless explicitly included."], checklist: ["Agree allowed destination classes before running checks.", "Correlate receiver logs with the application request.", "Separate browser-originated fetches from server-originated requests."] },
      { title: "Check destination changes", paragraphs: ["A validated initial URL can lead elsewhere through a redirect or a later DNS resolution. Review how the fetcher handles redirects and how it validates the actual connection destination. A fixed business integration should not silently become a general-purpose network client."], source: 0 },
      { title: "Describe the reachable boundary", paragraphs: ["A callback proves a request reached the test receiver. It does not prove access to a database, a metadata credential service, or another tenant. Report the observed destination, method, request data, response exposure, and any tested restrictions separately."], checklist: ["Retest the denied destination class with a safe fixture.", "Preserve a legitimate import or webhook delivery test.", "Review outbound controls as well as URL validation code."] },
    ],
    limitations: "Out-of-band callbacks may be delayed, retried, or produced by a proxy. Internal reachability and credential access need independent evidence and explicit scope. A public callback alone does not justify the highest possible SSRF impact.",
    faqs: [
      { question: "Does URL syntax validation prevent SSRF?", answer: "A syntactically valid URL can still point at an unintended destination. Review the allowed host or address policy and the actual outbound connection." },
      { question: "Should every URL fetcher use an allowlist?", answer: "A fixed integration can usually define allowed destinations. A public URL importer needs a different design that restricts unsafe destination classes and enforces network boundaries." },
      { question: "What evidence confirms a server-side request?", answer: "A unique marker in controlled receiver logs, correlated with the tested feature, supports that conclusion. Record whether a browser, gateway, or background worker could also have made the request." },
    ],
    sources: [{ title: "OWASP Server Side Request Forgery Prevention Cheat Sheet", url: cheatSheet("Server_Side_Request_Forgery_Prevention") }],
    related: ["attack-surface-inventory", "api-rate-limiting", "security-testing-report"],
  },
  {
    slug: "graphql-security-testing",
    title: "GraphQL security testing beyond endpoint discovery",
    description: "Assess GraphQL resolver permissions, field exposure, mutations, and query resource controls with known test data and bounded requests.",
    category: "API security",
    answer: "GraphQL security testing examines what a caller can read or mutate through the schema and how much work a query can cause. A single GraphQL endpoint can expose many distinct permission decisions, so assess resolvers, objects, and fields rather than counting URLs.",
    updated: UPDATED,
    sections: [
      { title: "Inventory operations and data relationships", paragraphs: ["Use an owner-provided schema or approved introspection output to identify queries, mutations, and nested object relationships. For a project application, list who may see project metadata, member details, and billing fields before choosing test operations."], checklist: ["Record the schema version and authenticated role.", "Identify deprecated fields still callable by clients.", "Include mutation operations as well as read queries."] },
      { title: "Test resolver and field permissions", paragraphs: ["Authorization needs to hold when an object is reached directly and through a relationship. With two test users, compare the same known record through each path. Check sensitive field exposure separately from access to the surrounding object."], source: 0 },
      { title: "Review query cost controls safely", paragraphs: ["Depth, list sizes, batching, and repeated operations can increase server work. Agree a small request budget and inspect configured cost limits before sending heavier queries. Observe rejection and worker behavior without trying to exhaust a live service."], source: 0, checklist: ["Use small seeded collections and capped pagination.", "Record which limit was enforced and the rejection response.", "Confirm ordinary client queries still complete."] },
      { title: "Retest the permission path", paragraphs: ["An error in the GraphQL envelope may coexist with data from other fields. Inspect both data and errors when evaluating a denial. A repair should stop protected fields from being returned while preserving the caller's authorized fields and operations."] },
    ],
    limitations: "A discovered schema or enabled introspection is not automatically a data access vulnerability. Query complexity tests require availability limits. Missing role fixtures leave resolver authorization incompletely assessed.",
    faqs: [
      { question: "Is one GraphQL endpoint one security test?", answer: "No. Each operation, object relationship, and sensitive field can enforce a different access rule. Coverage should describe those decisions." },
      { question: "Does disabling introspection fix GraphQL access control?", answer: "No. Hiding schema discovery does not establish that resolvers authorize callers. Review permissions even when the schema is supplied privately." },
      { question: "Can a GraphQL error response still expose data?", answer: "Yes. Inspect the full response because some fields can succeed while others return errors. The protected data itself determines whether the boundary held." },
    ],
    sources: [{ title: "OWASP GraphQL Cheat Sheet", url: cheatSheet("GraphQL") }],
    related: ["bola-testing", "api-rate-limiting", "access-control-testing"],
  },
  {
    slug: "openapi-security-testing",
    title: "Use OpenAPI to plan API security testing",
    description: "Turn an OpenAPI document into an assessment inventory, verify security declarations against runtime behavior, and record undocumented coverage gaps.",
    category: "API security",
    answer: "An OpenAPI document helps plan API security testing by describing operations, parameters, request bodies, and declared authentication schemes. Treat it as an inventory input, then verify that the deployed service enforces the intended requirements.",
    updated: UPDATED,
    sections: [
      { title: "Confirm the document matches the target", paragraphs: ["Record the document version and the deployment it describes. Review server URLs before importing anything into a scanner. A specification might point to a production service, a partner endpoint, or an obsolete environment outside the agreed scope."], checklist: ["Accept only approved target origins.", "Resolve references with the same scope and data handling limits.", "Compare sample operations with actual deployed routes."] },
      { title: "Review declared security requirements", paragraphs: ["OpenAPI defines security schemes and operation-level security requirements. Those declarations describe an API contract; they do not enforce access by themselves. Identify intentionally public operations and overrides so they can be checked against the product's policy."], source: 0 },
      { title: "Build useful request fixtures", paragraphs: ["Schema-valid input helps a test reach application logic instead of failing at validation. Replace example identifiers with disposable records created for the assessment. Fill required fields with harmless values and avoid blindly executing every documented mutation."], checklist: ["Supply separate test identities for relevant roles.", "Distinguish missing authentication from forbidden object access.", "Mark destructive or expensive operations for separate review."] },
      { title: "Report inventory and runtime gaps", paragraphs: ["Keep a ledger of documented operations exercised, operations skipped, and runtime routes absent from the document. A completed specification import does not mean every business workflow or permission rule was tested. Retest both the contract and implementation after changes."], source: 1 },
    ],
    limitations: "OpenAPI can be incomplete or stale and may omit business rules, state transitions, and object ownership. Automated request generation requires valid fixtures and scope controls. A schema mismatch can be a documentation issue rather than a confirmed vulnerability.",
    faqs: [
      { question: "Does an OpenAPI security scheme protect the API?", answer: "No. The server or gateway must enforce the required authentication and authorization. The specification describes the contract used to plan and verify tests." },
      { question: "Can an assessment use a private OpenAPI file?", answer: "Yes, when the owner authorizes its use. Keep credentials and sensitive example data out of the file and verify that referenced servers belong to scope." },
      { question: "What if the API has undocumented routes?", answer: "Record them as an inventory gap and assess approved routes separately. Do not silently count specification coverage as complete runtime coverage." },
    ],
    sources: [{ title: "OpenAPI Specification", url: "https://spec.openapis.org/oas/latest.html" }, { title: "OWASP REST Assessment Cheat Sheet", url: cheatSheet("REST_Assessment") }],
    related: ["attack-surface-inventory", "bola-testing", "security-testing-report"],
  },
  {
    slug: "cors-security-testing",
    title: "CORS security testing: verify browser data access",
    description: "Assess cross-origin resource sharing by connecting allowed origins, credentials, and sensitive responses to real browser behavior.",
    category: "Web security",
    answer: "CORS testing checks which browser origins may read an API response and whether credentialed requests expose protected data. A permissive header is a starting signal; the assessment needs the endpoint's data sensitivity, credential behavior, and a browser-readable response.",
    updated: UPDATED,
    sections: [
      { title: "Identify intended browser clients", paragraphs: ["Write down the web origins that legitimately call the API. An origin includes scheme, host, and port. Public data used by many websites can require a different policy from an authenticated account export."], source: 0 },
      { title: "Compare allowed and untrusted origins", paragraphs: ["In a controlled test, inspect response headers for a known allowed origin and a separate origin you own that should be denied. Check the actual sensitive response, not only a preflight route or a generic error."], checklist: ["Record Access-Control-Allow-Origin and credential-related headers.", "Check whether the API uses cookies, explicit bearer tokens, or public access.", "Separate an API's CORS policy from its ordinary authentication policy."] },
      { title: "Verify browser behavior", paragraphs: ["A command-line client does not enforce browser CORS rules. Use a harmless browser proof in an authorized session to establish whether the untrusted origin can read protected test data. Keep the demonstration confined to your own account and test records."], checklist: ["Confirm the browser actually sends the relevant credentials.", "Inspect whether the response is readable by the test page.", "Record browser errors and credential restrictions as part of the result."] },
      { title: "Keep CORS and authorization distinct", paragraphs: ["The server still needs to protect the endpoint against unauthorized callers. Tightening CORS changes browser response sharing; it does not prevent non-browser clients from sending requests. Retest legitimate frontend calls after narrowing the origin policy."], source: 0 },
    ],
    limitations: "Wildcard access to intentionally public data is not inherently a vulnerability. A reflected origin header does not prove credentialed data theft. Preflight results and HTTP clients alone cannot establish browser exploitability.",
    faqs: [
      { question: "Is Access-Control-Allow-Origin: * always unsafe?", answer: "No. It can be appropriate for deliberately public resources. Evaluate whether protected data is readable from an unintended browser origin." },
      { question: "Does CORS block unauthorized API requests?", answer: "CORS governs browser access to responses. API authentication and authorization must protect data and state independently." },
      { question: "Why test the final response after preflight?", answer: "A preflight describes whether a browser may attempt certain cross-origin requests. The final response and browser credential behavior determine what the requesting page can read." },
    ],
    sources: [{ title: "OWASP REST Security Cheat Sheet: CORS", url: `${cheatSheet("REST_Security")}#cors` }],
    related: ["csrf-testing", "session-security-testing", "security-header-testing"],
  },
  {
    slug: "security-header-testing",
    title: "Security header testing with application context",
    description: "Review HTTP security headers across real application responses, prioritize practical browser protections, and avoid treating a header score as a pentest.",
    category: "Web security",
    answer: "Security header testing checks whether HTTP responses deliver useful browser protections for the application. Review actual policies on HTML, authenticated responses, errors, and redirects, then connect any gap to its relevant behavior rather than relying on a single score.",
    updated: UPDATED,
    sections: [
      { title: "Check representative response types", paragraphs: ["The homepage may be served by a different layer from the account dashboard or API. Record headers on a public page, a signed-in page, an error response, and any relevant redirect. Compare the final response with gateway and application configuration."], checklist: ["Keep the full redirect chain in your assessment notes.", "Identify which responses contain sensitive data or active HTML.", "Repeat checks on the canonical origin used by customers."] },
      { title: "Assess protection and compatibility", paragraphs: ["HSTS affects HTTPS use, frame restrictions affect embedding, and nosniff affects MIME interpretation. Different response types need different protections. Avoid adding obsolete headers solely to improve a score, and review subdomain readiness before broad transport policies."], source: 0 },
      { title: "Prioritize the exposed behavior", paragraphs: ["A missing frame restriction on a page with sensitive actions is different from its absence on an image. State which browser behavior remains possible and whether another policy already covers it. Separate a configuration recommendation from a demonstrated attack path."], checklist: ["Review content type and cache behavior on account exports.", "Check intended iframe integrations before restricting embedding.", "Document the route and response type for each recommendation."] },
      { title: "Retest legitimate application journeys", paragraphs: ["A policy change can affect checkout, identity providers, previews, or embedded dashboards. Verify the intended browser journeys after deployment and recheck the response headers that customers actually receive. Keep a rollback plan for policies that can make a site inaccessible."] },
    ],
    limitations: "Headers are one protection layer. They do not establish secure server-side permissions, query construction, or business logic. A homepage-only check cannot describe every application route, and a numerical grade is not a vulnerability assessment.",
    faqs: [
      { question: "Do perfect header scores prove a site is secure?", answer: "No. Header checks cover a narrow set of browser and response protections. Authentication, authorization, input handling, and workflows need separate assessment." },
      { question: "Should APIs have the same headers as HTML pages?", answer: "Evaluate the response's use. A JSON API and an interactive HTML page have different browser behavior, although both may need appropriate content types and sensitive-data cache controls." },
      { question: "Why can a header fix break the site?", answer: "Policies can restrict scripts, frames, network calls, or transport behavior used by legitimate features. Test those features and the deployed headers together." },
    ],
    sources: [{ title: "OWASP HTTP Headers Cheat Sheet", url: cheatSheet("HTTP_Headers") }],
    related: ["content-security-policy", "cors-security-testing", "session-security-testing"],
  },
  {
    slug: "content-security-policy",
    title: "Content Security Policy: assess and roll out CSP",
    description: "Plan Content Security Policy around real browser dependencies, distinguish report-only from enforcement, and retest scripts, frames, and checkout flows.",
    category: "Web security",
    answer: "Content Security Policy (CSP) tells a browser which sources and behaviors a page permits. Assess the policy against the page's real dependencies, observe violations, and test enforcement. A report-only policy provides visibility but does not block the reported behavior.",
    updated: UPDATED,
    sections: [
      { title: "Inventory the page's dependencies", paragraphs: ["List scripts, styles, images, frames, forms, and outbound browser connections used by representative journeys. Separate public marketing pages from signed-in tools. A payment integration may need permissions that should not be copied to every route."], checklist: ["Include sign-in, checkout, exports, and embedded widgets.", "Record exact dependency origins rather than broad wildcards.", "Identify inline code and the framework's CSP support."] },
      { title: "Distinguish observation from enforcement", paragraphs: ["Content-Security-Policy-Report-Only records violations without enforcing the policy. It can help find missing legitimate dependencies during rollout. Keep that state visible in the assessment so an observation-only configuration is not reported as a blocking control."], source: 0 },
      { title: "Evaluate the policy's actual restrictions", paragraphs: ["A long policy can still allow broad script execution. Review source allowances, inline script handling, framing, and form destinations against the application's risk. CSP complements safe rendering; it should not become the reason to leave unsafe HTML insertion unaddressed."], source: 0, checklist: ["Check both the browser console and the served policy header.", "Verify which directives protect the action being assessed.", "Keep expected violations separate from successful blocking evidence."] },
      { title: "Roll out and verify a complete journey", paragraphs: ["After enabling enforcement, run the product's normal browser journeys and inspect blocked requests. Tighten route policies gradually when dependencies differ. Retain a known-good configuration so a failed rollout can be recovered without removing every restriction."] },
    ],
    limitations: "CSP depends on browser support and the policy actually served. Report-only mode is not prevention. CSP cannot establish server-side access control, and broad allowances can reduce its protection even when the header is present.",
    faqs: [
      { question: "Does report-only CSP stop XSS?", answer: "Report-only mode does not enforce the policy. It supplies violation information for assessment and rollout. Blocking requires an enforced policy, alongside safe application rendering." },
      { question: "Should every page share one CSP?", answer: "Only when their dependency and behavior requirements match. A narrow policy for a static page may differ from one supporting a signed-in application or payment provider." },
      { question: "Is having a CSP header enough?", answer: "No. Review the directives, allowed sources, and browser behavior. A permissive policy can be present while offering little protection for the action under review." },
    ],
    sources: [{ title: "OWASP Content Security Policy Cheat Sheet", url: cheatSheet("Content_Security_Policy") }],
    related: ["xss-testing", "security-header-testing", "remediation-retesting"],
  },
  {
    slug: "exposed-secrets",
    title: "Exposed secrets: validate, contain, and remediate",
    description: "Handle suspected keys and credentials in public files without leaking them further, distinguish public identifiers, and plan safe rotation and verification.",
    category: "Web security",
    answer: "An exposed secret is sensitive credential material available outside its intended trust boundary. Assess where it was disclosed, what access it could authorize, and whether it remains active. Minimize handling, notify the owner, and rotate or revoke through the proper provider controls.",
    updated: UPDATED,
    sections: [
      { title: "Classify the value before escalating", paragraphs: ["A public client identifier, a sample placeholder, and a private API credential require different treatment. Record the file, deployment, and surrounding configuration that suggest the value's purpose. Do not assume a string is a working secret because it resembles a key format."], checklist: ["Save a redacted fingerprint rather than the full credential.", "Identify whether the file is public, private, or intentionally distributed.", "Ask the owner to map the value to its provider and permissions."] },
      { title: "Validate with the smallest approved check", paragraphs: ["Prefer owner-assisted provider inspection to using the credential against production data. If active verification is approved, limit it to a read-only capability check designed for that provider. Never place a found secret in a public issue, browser URL, or analytics event."], checklist: ["Keep the credential out of report screenshots and request logs.", "Record the approved verification method and its result.", "Stop if validation could access another party's data."] },
      { title: "Rotate the credential and remove disclosure", paragraphs: ["Deleting a visible file does not revoke a credential already copied. Coordinate replacement and revocation, update dependent services, and remove the exposed material from the current distribution. Rotation needs verification because an incomplete change can interrupt legitimate integrations."], source: 0 },
      { title: "Check the full distribution path", paragraphs: ["Recheck public assets, build artifacts, source maps, downloaded reports, and caches involved in the original exposure. Use the redacted fingerprint to track locations. Confirm the application works with the replacement and that the old secret's permissions are no longer usable."] },
    ],
    limitations: "A format match is a candidate, not proof of active credentials. Provider-specific permission and revocation behavior varies. Removing source text cannot erase copies already downloaded, so the response must include the credential's lifecycle.",
    faqs: [
      { question: "Is a public API key always a secret?", answer: "No. Some identifiers are designed for browser distribution. Evaluate the provider's model, restrictions, permissions, and other controls before labeling the exposure." },
      { question: "Does deleting the file solve a credential leak?", answer: "It removes one disclosure path but does not invalidate previously copied credentials. Review revocation or rotation and verify dependent services afterward." },
      { question: "Should a report include the full secret as proof?", answer: "Use redacted evidence and a fingerprint sufficient for the owner to identify it. Share sensitive material only through the agreed protected process when necessary." },
    ],
    sources: [{ title: "OWASP Secrets Management Cheat Sheet", url: cheatSheet("Secrets_Management") }],
    related: ["attack-surface-inventory", "security-testing-report", "remediation-retesting"],
  },
  {
    slug: "session-security-testing",
    title: "Session security testing from login to logout",
    description: "Assess session creation, cookie scope, privilege changes, expiry, and logout with real server requests and known test accounts.",
    category: "Identity and access",
    answer: "Session security testing checks how authenticated state is created, carried, changed, and invalidated. Use a test account to verify cookie protections and whether protected requests remain usable after logout, expiry, or a relevant permission change.",
    updated: UPDATED,
    sections: [
      { title: "Map the authentication state", paragraphs: ["Identify whether the application uses server sessions, bearer tokens, refresh tokens, or a combination. Record where each value is stored and which requests use it. A cookie name or token shape alone does not explain the revocation model."], checklist: ["Follow login, refresh, logout, and account-switching journeys.", "Keep raw tokens out of shared screenshots and reports.", "Distinguish application state from identity-provider state."] },
      { title: "Review browser cookie protections", paragraphs: ["For cookie-based sessions, inspect Secure, HttpOnly, SameSite, domain, path, and expiry in the actual Set-Cookie response. The scope should match where the cookie is needed. Cookie attributes reduce particular risks but do not replace a valid session check on the server."], source: 0 },
      { title: "Test transitions and invalidation", paragraphs: ["Capture a harmless authenticated request, log out, and repeat that request with the old test session. Repeat for a privilege change and a documented expiry boundary. For distributed identity systems, record the stated revocation delay instead of assuming all token types are immediately invalidated."], checklist: ["Verify server responses rather than only the logged-out screen.", "Check that a newly signed-in session still works.", "Record the token type and transition time for each result."] },
      { title: "Review fixation and renewal behavior", paragraphs: ["Session identity should change appropriately when a caller moves into a higher privilege state. Compare pre-login and post-login session handling without sharing tokens across real users. Add transition tests alongside regular sign-in tests so future login changes preserve the boundary."], source: 0 },
    ],
    limitations: "Token revocation and timeout behavior depends on the application's architecture and documented policy. A cleared cookie only proves a browser-side change. One tested session type does not cover refresh tokens, other devices, or federated identity sessions.",
    faqs: [
      { question: "Does clearing a cookie prove logout is secure?", answer: "No. Test whether the old authenticated state can still access a protected endpoint, and evaluate that result against the application's session or token revocation policy." },
      { question: "Does HttpOnly prevent every XSS impact?", answer: "HttpOnly restricts script access to the cookie. Unsafe scripts may still perform actions within the page's authenticated context, so rendering defects require their own fix." },
      { question: "Should permission changes affect existing sessions?", answer: "Define the expected policy, especially for sensitive roles. Test whether the server applies updated permissions or requires renewed authentication as designed." },
    ],
    sources: [{ title: "OWASP Session Management Cheat Sheet", url: cheatSheet("Session_Management") }],
    related: ["authentication-security-testing", "csrf-testing", "access-control-testing"],
  },
  {
    slug: "authentication-security-testing",
    title: "Authentication security testing across account journeys",
    description: "Plan authentication assessment across sign-in, recovery, MFA, and sensitive account changes, with bounded tests and clear identity-provider limits.",
    category: "Identity and access",
    answer: "Authentication testing examines how an application establishes a caller's identity and protects sensitive account transitions. Cover ordinary login, recovery, MFA enrollment, and identity changes using dedicated accounts and the owner's expected security policy.",
    updated: UPDATED,
    sections: [
      { title: "List every way to establish identity", paragraphs: ["Password login is only one entry point. List social sign-in, magic links, recovery, device enrollment, API credentials, and administrative impersonation if the product supports them. Identify which controls belong to the application and which belong to an external identity provider."], checklist: ["Record the supported flows rather than assuming all products use passwords.", "Use accounts and inboxes created for the assessment.", "Agree limits for unsuccessful sign-in and recovery requests."] },
      { title: "Review failures and sensitive changes", paragraphs: ["Evaluate account enumeration, throttling, MFA behavior, and reauthentication for sensitive actions. Apply the relevant controls to the whole identity journey. Strong login protection loses value if an account can be reassigned through a weaker change-email or recovery path."], source: 0 },
      { title: "Use bounded negative cases", paragraphs: ["Compare a valid login with a small number of approved invalid attempts. Observe response behavior and rate controls without conducting a password attack. For MFA, test the intended enrollment, recovery, and removal sequence with the owner's fixtures."], checklist: ["Do not use leaked credentials or real user accounts.", "Verify a failed attempt does not establish authenticated state.", "Keep delivery delays distinct from token validation failures."] },
      { title: "Check account transitions end to end", paragraphs: ["After an email change, recovery, or identity unlink, verify which address receives security notifications and which identity can sign in. Repeat a harmless protected operation to establish the resulting account access. Capture the expected transition policy in regression tests."] },
    ],
    limitations: "An application assessment does not authorize attacks on its identity provider or real users. Account lockout, provider restrictions, and message delivery can obscure results. Authentication success does not establish that authorization rules are correct.",
    faqs: [
      { question: "Is authentication testing just checking passwords?", answer: "No. Recovery, MFA, session creation, identity linking, and sensitive account changes can establish or alter access and need assessment when supported." },
      { question: "Can a scanner assess a third-party login provider?", answer: "The provider is a separate scope and control boundary. An application test can review its integration, but testing provider infrastructure needs separate authorization." },
      { question: "Does successful login prove account security?", answer: "It establishes that one expected identity flow worked. Permission enforcement, recovery, session invalidation, and other account transitions need separate checks." },
    ],
    sources: [{ title: "OWASP Authentication Cheat Sheet", url: cheatSheet("Authentication") }],
    related: ["password-reset-security", "session-security-testing", "access-control-testing"],
  },
  {
    slug: "csrf-testing",
    title: "CSRF testing for authenticated browser actions",
    description: "Review cross-site request forgery around state-changing requests, token validation, cookie behavior, and safe browser confirmation.",
    category: "Web security",
    answer: "Cross-site request forgery (CSRF) can cause a user's browser to submit an unintended authenticated action. Assess state-changing endpoints, how the browser supplies credentials, and whether the server validates an appropriate anti-CSRF control before applying the change.",
    updated: UPDATED,
    sections: [
      { title: "Inventory actions and credentials", paragraphs: ["List account changes, invitations, exports, and other actions that affect state. Identify whether credentials are automatically supplied by the browser or explicitly attached by application code. Check whether any nominally read-only request performs a write."], checklist: ["Use reversible changes in a disposable account.", "Record the method, content type, and credential mechanism.", "Include normal forms as well as JavaScript-driven actions."] },
      { title: "Review server validation", paragraphs: ["Framework CSRF protections, request tokens, origin checks, and cookie settings can contribute to protection. A token present in the request is not evidence that the server validates it. Test approved cases with missing or mismatched controls and verify the state did not change."], source: 0 },
      { title: "Confirm the browser path safely", paragraphs: ["Use an origin and account you control to evaluate the candidate browser interaction. Observe whether the browser sends the relevant cookies and whether the server accepts the harmless action. An HTTP client that manually attaches credentials cannot reproduce all browser restrictions."], checklist: ["Verify the resulting application state, not only the status code.", "Restore the test account's setting after confirmation.", "Record blocked requests and their rejection reason."] },
      { title: "Consider same-site boundaries", paragraphs: ["SameSite is defined around sites rather than individual origins. A sibling subdomain may belong to the same site even when it is controlled differently. Review untrusted subdomain hosting and legitimate cross-site flows when choosing controls, then retest normal sign-in and payment redirects."], source: 0 },
    ],
    limitations: "The absence of a visible CSRF token is not proof of vulnerability. Other validated controls or credential models may prevent the browser path. State changes must be harmless, reversible, and inside the agreed test scope.",
    faqs: [
      { question: "Is SameSite always enough to prevent CSRF?", answer: "Its protection depends on cookie settings, endpoint behavior, and the application's site boundaries. Evaluate the complete request path instead of assuming one attribute covers every action." },
      { question: "Can GET requests have a CSRF risk?", answer: "If a GET request changes state, browser navigation can create a relevant request path. Identify and repair state-changing behavior on methods intended for safe reads." },
      { question: "Does a rejected request prove the fix worked?", answer: "Check that the intended state remained unchanged and a valid request still succeeds. An error response alone can hide an action that already ran." },
    ],
    sources: [{ title: "OWASP Cross-Site Request Forgery Prevention Cheat Sheet", url: cheatSheet("Cross-Site_Request_Forgery_Prevention") }],
    related: ["session-security-testing", "cors-security-testing", "business-logic-testing"],
  },
  {
    slug: "file-upload-security",
    title: "File upload security testing through storage and download",
    description: "Assess file uploads from acceptance to retrieval, including type checks, storage permissions, processing boundaries, and safe test fixtures.",
    category: "Web security",
    answer: "File upload testing reviews how an application accepts, processes, stores, and serves user-controlled files. Use harmless fixtures to assess permitted formats and access rules, then follow the file through preview, download, and background processing.",
    updated: UPDATED,
    sections: [
      { title: "Define the intended file contract", paragraphs: ["A profile image, document attachment, and data import have different allowed formats and processing needs. Document file types, size limits, ownership, and whether the content becomes public. This prevents a test from treating a deliberately supported format as a vulnerability."], checklist: ["Create small harmless examples of each permitted format.", "Identify previewers, converters, scanners, and storage services.", "Agree separate limits for archives or expensive conversion jobs."] },
      { title: "Review layered acceptance controls", paragraphs: ["Filename extensions and client-provided MIME types are insufficient as a single defense. Review type validation, safe naming, size restrictions, processing libraries, and where files are stored. The controls should reflect how the application will later interpret the file."], source: 0 },
      { title: "Test ownership after upload", paragraphs: ["Upload a known file as account A, then check its metadata, preview, and download routes from authorized test account B. Include generated thumbnails and extracted text when those are separate resources. Verify that public sharing is an explicit product action rather than a storage default."], checklist: ["Record whether URLs are public, signed, or authorization-protected.", "Check access again after sharing is removed.", "Keep test filenames and content free of personal information."] },
      { title: "Retest cleanup and serving behavior", paragraphs: ["Deletion can remove a database record while leaving the object or preview available. Check the product's retention policy and observed access after deletion. Review the download response's content type and disposition alongside the upload validation."] },
    ],
    limitations: "Harmless fixtures can verify selected acceptance and access rules but cannot prove that every parser is safe. Malware samples, executable files, archive bombs, and resource exhaustion checks require a separate approved environment and test plan.",
    faqs: [
      { question: "Is checking the file extension enough?", answer: "No. Review the actual permitted format, content checks, processing path, storage location, and serving behavior as a set of controls." },
      { question: "Can a successful upload still have access control problems?", answer: "Yes. Preview, download, generated artifacts, and shared links can expose the file through separate routes. Assess each relevant resource boundary." },
      { question: "Does deleting an attachment remove every copy?", answer: "That depends on the application's storage, cache, and retention design. Verify access to the original object and derived artifacts against the stated deletion policy." },
    ],
    sources: [{ title: "OWASP File Upload Cheat Sheet", url: cheatSheet("File_Upload") }],
    related: ["bola-testing", "xss-testing", "attack-surface-inventory"],
  },
  {
    slug: "password-reset-security",
    title: "Password reset security from request to recovery",
    description: "Test password recovery using dedicated inboxes, token lifecycle checks, account binding, and session policy without accessing real users' accounts.",
    category: "Identity and access",
    answer: "Password reset testing checks whether the recovery process proves control of the intended account and safely changes its credentials. Assess request behavior, delivery, token binding and expiry, reuse, and the resulting session policy using accounts created for testing.",
    updated: UPDATED,
    sections: [
      { title: "Separate request, delivery, and completion", paragraphs: ["A recovery request, its email delivery, and the final password change are distinct steps. Create two owned test accounts and inboxes, then record which account requested recovery and which account the completion affects. A delayed email is not automatically a token-validation flaw."], checklist: ["Avoid sending recovery messages to real users.", "Agree a small request budget to protect delivery and account access.", "Redact recovery links and codes in evidence."] },
      { title: "Review the token lifecycle", paragraphs: ["Recovery tokens need appropriate randomness, secure handling, account binding, limited lifetime, and single-use behavior. Review the provider or implementation with the owner. A long-looking token is not sufficient evidence that its generation and validation are sound."], source: 0 },
      { title: "Verify invalid and completed states", paragraphs: ["Use the test account's recovery link once, then verify that reuse cannot perform another change. Test the documented expired state and a token associated with the other fixture account. Compare failures with a fresh valid recovery so delivery or environment problems do not look like successful protection."], checklist: ["Check the account that actually changed, not only the confirmation screen.", "Confirm the old and new login behavior using the test account.", "Keep reset completion separate from MFA recovery assessment."] },
      { title: "Check post-recovery access", paragraphs: ["Verify notifications and existing-session behavior against the account recovery policy. A credential change should not quietly redirect control to an unverified address. Retest normal login after recovery and record any deliberate session revocation delay."] },
    ],
    limitations: "Email delivery, identity-provider controls, and rate limits can prevent completion without demonstrating correct token handling. MFA recovery is a separate journey. Expensive guessing and real-user recovery attempts are outside a harmless fixture assessment.",
    faqs: [
      { question: "Should a reset link work more than once?", answer: "A completed recovery token should not authorize another reset. Verify the product's token invalidation behavior with a test account and a fresh control link." },
      { question: "Does a reset email prove the flow is secure?", answer: "It only establishes delivery to that inbox. Account binding, token validation, expiry, completion, and session behavior need separate checks." },
      { question: "Can recovery reveal whether an account exists?", answer: "Differences in messages or behavior can create an enumeration signal. Use owned fixtures to assess that signal without contacting or probing real customers." },
    ],
    sources: [{ title: "OWASP Forgot Password Cheat Sheet", url: cheatSheet("Forgot_Password") }],
    related: ["authentication-security-testing", "session-security-testing", "api-rate-limiting"],
  },
  {
    slug: "api-rate-limiting",
    title: "API rate limiting: assess abuse and resource controls",
    description: "Evaluate API request budgets, account quotas, expensive operations, and safe rejection behavior without attempting to exhaust a live service.",
    category: "API security",
    answer: "API rate limiting controls how often a caller can use a resource, while quotas and concurrency limits bound other forms of consumption. Assess the actual expensive or sensitive operation with a small agreed test budget, and verify enforcement without creating an availability incident.",
    updated: UPDATED,
    sections: [
      { title: "Identify what needs a limit", paragraphs: ["Login attempts, email delivery, report generation, image conversion, and ordinary reads have different costs. List the action, cost, intended caller, and business entitlement. A single requests-per-IP rule may not describe the account's resource budget."], checklist: ["Identify message-delivery and third-party billing costs.", "Record account, tenant, endpoint, and global limits where relevant.", "Distinguish request count from queued work and concurrent jobs."] },
      { title: "Set a safe validation budget", paragraphs: ["Inspect configured limits with the owner and choose a test threshold in staging where possible. Monitor a small set of requests around that threshold. Availability testing should stop if normal service is affected, even when the planned request count has not been reached."], source: 0 },
      { title: "Check enforcement and recovery", paragraphs: ["Verify whether rejected work actually remains unperformed. A rate-limited response that still queues an email or report does not enforce the intended cost boundary. Observe recovery after the documented window and check that another authorized test account's allowance behaves as designed."], checklist: ["Inspect the action outcome as well as the response code.", "Record the limit key, window, and test account.", "Confirm normal traffic resumes after the restriction expires."] },
      { title: "Report limits that remain unknown", paragraphs: ["A short sample may establish one configured threshold but not every global or distributed limit. Record whether the test covered a single worker or the deployed service. Put load capacity, deliberate exhaustion, and DDoS resilience into a separate approved assessment rather than inferring them from a few 429 responses."] },
    ],
    limitations: "A missing rate-limit header does not prove no limit exists. A short test cannot establish capacity or DDoS resilience. Provider delivery limits and shared capacity can affect observations, so preserve the configured policy and measured scope.",
    faqs: [
      { question: "Does a 429 response prove resource protection?", answer: "It proves the request received a limiting response. Check whether the expensive operation still ran and whether the limit covers the intended caller and resource." },
      { question: "Should all endpoints share the same rate limit?", answer: "Choose limits around endpoint cost, abuse risk, legitimate demand, and entitlements. An inexpensive read and an email-sending operation can require different controls." },
      { question: "Can rate limiting be tested safely in production?", answer: "Only within an explicitly agreed small budget and with monitoring and stop conditions. Prefer staging or a dedicated test threshold for heavier validation." },
    ],
    sources: [{ title: "OWASP Denial of Service Cheat Sheet: rate limiting", url: `${cheatSheet("Denial_of_Service")}#rate-limiting` }],
    related: ["graphql-security-testing", "business-logic-testing", "pentest-scope-authorization"],
  },
  {
    slug: "saas-tenant-isolation",
    title: "SaaS tenant isolation testing across shared services",
    description: "Assess SaaS workspace boundaries with separate tenants, including database records, caches, files, exports, and delayed background work.",
    category: "Identity and access",
    answer: "Tenant isolation testing verifies that one customer's users and services cannot reach another customer's protected data or actions. Create two dedicated test tenants and trace the tenant boundary through requests, storage, caches, exports, and background jobs.",
    updated: UPDATED,
    sections: [
      { title: "Define tenant ownership and shared data", paragraphs: ["Some data is tenant-owned while other data is deliberately global, such as a public template catalog. Classify the record types and allowed platform operations before testing. A support administrator with explicit cross-tenant permission is a different policy case from a regular tenant member."], checklist: ["Create distinct fixture tenants and known records in each.", "Identify legitimate shared objects and platform roles.", "Document service identities that are intentionally cross-tenant."] },
      { title: "Verify the selected tenant", paragraphs: ["A tenant identifier supplied by a client should select a context only when the authenticated caller is allowed to use it. Review how that context reaches data access and permission decisions. Changing a tenant selector must not silently change the caller's authority."], source: 0 },
      { title: "Follow data beyond the main API", paragraphs: ["A correctly scoped query can still feed an incorrectly shared cache or export. Read the same fixture route from both tenants, then inspect generated files and delayed job results. If a job runs after a member is removed, compare its authorization behavior with the product's stated policy."], checklist: ["Cover cache hits as well as fresh data reads.", "Include attachments, thumbnails, exports, and download links.", "Record which tenant receives each background job's result."] },
      { title: "Retest the complete isolation boundary", paragraphs: ["Repairing one endpoint does not establish that storage or worker boundaries are correct. Add negative cross-tenant tests and positive same-tenant controls at the affected layer. Recheck member removal and resource deletion when either changes the expected access."], source: 0 },
    ],
    limitations: "Two tenants exercise selected boundaries rather than every customer configuration. Platform support access, shared catalogs, and service accounts require explicit policy. Infrastructure isolation and backup restoration need their own environment-level evidence.",
    faqs: [
      { question: "Does a separate workspace ID prove tenant isolation?", answer: "No. The server must bind tenant selection to an authorized identity and preserve the boundary across the components that handle tenant-owned data." },
      { question: "Which SaaS routes are often missed in a test?", answer: "Generated exports, download URLs, cached responses, and delayed jobs can use access paths different from the main object route. Include those paths when the product supports them." },
      { question: "Is every cross-tenant response a vulnerability?", answer: "Evaluate the documented policy. Deliberately public data or an explicitly authorized platform operation can be valid; regular users accessing another tenant's protected data is a different case." },
    ],
    sources: [{ title: "OWASP Multi Tenant Security Cheat Sheet", url: cheatSheet("Multi_Tenant_Security") }],
    related: ["bola-testing", "access-control-testing", "business-logic-testing"],
  },
  {
    slug: "business-logic-testing",
    title: "Business logic testing with state and invariants",
    description: "Assess workflow rules, repeated actions, stale states, and account entitlements with safe fixtures and outcomes tied to real business impact.",
    category: "Testing workflow",
    answer: "Business logic testing checks whether application workflows preserve their intended rules, including order, eligibility, one-time effects, and ownership. Write the expected invariant, exercise controlled state transitions, and verify the resulting record or entitlement rather than only the page response.",
    updated: UPDATED,
    sections: [
      { title: "Write the invariant in plain language", paragraphs: ["Examples include one reward per eligible event, no report before verified payment, and no approval by the requesting user. Ask the product owner which outcomes must never occur. A broken user journey is a correctness issue; a security finding needs a rule failure with meaningful unauthorized impact."], checklist: ["Identify the actor, resource, prerequisite, and allowed outcome.", "Use sandbox transactions and disposable entitlements.", "Record which state transitions the owner authorizes you to exercise."] },
      { title: "Review server-side workflow state", paragraphs: ["The server needs to validate prerequisites and state transitions independently of page order. Inspect what happens when a completed action is repeated or a stale step is submitted. Sensitive effects need durable protection against unintended replay."], source: 0 },
      { title: "Exercise bounded alternate sequences", paragraphs: ["For a sandbox purchase, test cancellation, a repeated confirmation, and a return after session expiry. Verify which record becomes paid and which account receives the credit. Keep real charges, repeated financial transactions, and high-volume concurrency outside this fixture plan."], checklist: ["Check persisted outcomes after each approved sequence.", "Use a normal completed journey as the positive control.", "Restore fixtures and record cleanup at the end of testing."] },
      { title: "Fix the rule and its regression cases", paragraphs: ["Choose a repair at the layer that owns the invariant, such as the transaction or authorization boundary. Test the original failure sequence alongside ordinary retries and valid user flows. A UI disabled button alone cannot enforce a server-side one-time effect."] },
    ],
    limitations: "A tester cannot infer every business rule from the interface. Real-money, concurrency, or third-party side effects need a separate approved plan. A generic automated scan often lacks the state fixtures needed to assess product-specific invariants.",
    faqs: [
      { question: "Can a workflow be insecure without an injection bug?", answer: "Yes. Incorrect eligibility, ownership, ordering, or repeated effects can create unauthorized outcomes even when input is well formed." },
      { question: "Does a disabled button prevent repeated actions?", answer: "It improves the interface but does not enforce the rule at the server. The action endpoint and stored state need to handle repeats correctly." },
      { question: "How should a business logic finding describe impact?", answer: "State the violated rule and the unauthorized result demonstrated with test fixtures. Avoid claiming financial loss or account takeover that the evidence did not establish." },
    ],
    sources: [{ title: "OWASP Business Logic Security Cheat Sheet", url: cheatSheet("Business_Logic_Security") }],
    related: ["api-rate-limiting", "security-testing-report", "remediation-retesting"],
  },
  {
    slug: "pentest-scope-authorization",
    title: "Penetration test scope and authorization checklist",
    description: "Prepare a practical security testing scope with approved targets, roles, request limits, data handling, exclusions, and escalation contacts.",
    category: "Testing workflow",
    answer: "A security testing scope states which targets, identities, methods, and conditions are authorized. Agree it with the responsible owner before active testing, including exclusions, data handling, availability limits, and a contact who can stop or clarify the assessment.",
    updated: UPDATED,
    sections: [
      { title: "Define target and environment boundaries", paragraphs: ["List exact application origins, APIs, and environments rather than a broad brand name. Identify shared hosting, identity providers, payment services, and partner systems. A link or redirect from an approved page does not automatically bring its destination into scope."], checklist: ["Record the owner and environment for each target.", "Mark production and staging separately.", "Keep explicit excluded origins and services in the test configuration."] },
      { title: "Agree permitted techniques and limits", paragraphs: ["Rules of engagement connect assessment objectives with allowed methods, logistics, risk controls, and stop conditions. Choose request and concurrency limits, safe fixtures, and whether state changes are permitted. Use separate authorization for tests that could affect availability or external systems."], source: 0 },
      { title: "Prepare roles and sensitive evidence handling", paragraphs: ["Supply the identities needed for the agreed boundaries: for example a viewer, administrator, and users in two test tenants. Decide how request tokens, screenshots, records, and reports will be protected and retained. Missing accounts should become a visible coverage limit rather than an assumed pass."], checklist: ["Create dedicated test accounts and reversible fixture records.", "Define the secure report recipient and retention period.", "Record the escalation contact and pause procedure."] },
      { title: "Keep scope current during discovery", paragraphs: ["Discovery may reveal an undocumented API or another service boundary. Record it and ask the owner to resolve scope before active checks. For a vulnerability disclosure or bounty program, use that program's written scope and reporting terms instead of treating general good intent as authorization."], source: 1 },
    ],
    limitations: "This is an operational planning checklist, not a legal authorization template. The responsible parties must establish authority and applicable terms. Scope should be reviewed when the target, methods, provider constraints, or environment changes.",
    faqs: [
      { question: "Does owning a domain authorize testing every linked service?", answer: "No. Third-party destinations, shared infrastructure, and provider systems can have separate owners and terms. Identify and authorize each relevant boundary." },
      { question: "What should happen when a test needs a missing account?", answer: "Record the affected coverage as incomplete and obtain an appropriate fixture if possible. Do not count an unexercised role boundary as a passed check." },
      { question: "Can the scope change during an assessment?", answer: "Yes, when the responsible owner explicitly updates it. Record the change, permitted methods, and limits before performing the dependent active tests." },
    ],
    sources: [{ title: "NIST SP 800-115: security assessment planning and rules of engagement", url: "https://csrc.nist.gov/pubs/sp/800/115/final" }, { title: "OWASP Vulnerability Disclosure Cheat Sheet", url: cheatSheet("Vulnerability_Disclosure") }],
    related: ["attack-surface-inventory", "access-control-testing", "security-testing-report"],
  },
  {
    slug: "security-testing-report",
    title: "What a useful security testing report should contain",
    description: "Evaluate security reports for scope, reproducible evidence, calibrated impact, remediation, explicit coverage limits, and retest status.",
    category: "Testing workflow",
    answer: "A useful security testing report explains what was assessed, what evidence establishes each issue, why the observed impact matters, and how to repair and retest it. It should also identify skipped or inconclusive checks so an empty finding list is not mistaken for complete assurance.",
    updated: UPDATED,
    sections: [
      { title: "State scope, timing, and audience", paragraphs: ["Record the target environment, assessment dates, roles, methods, and limitations. Give decision makers a concise account of the main observed risks, then give engineers the details needed for repair. Assessment results describe the tested system at a point in time."], source: 0 },
      { title: "Connect evidence to the finding", paragraphs: ["For a cross-account export issue, show the test caller, the known owner, the export request, and the protected data returned. A screenshot of a scanner alert does not establish that chain. Use a stable finding ID and keep the evidence narrowly scoped to owned fixtures."], checklist: ["Describe expected behavior and the observed failure.", "Include a safe reproduction sequence and a valid control.", "Redact credentials, personal records, and unrelated response data."] },
      { title: "Keep confidence, severity, and coverage separate", paragraphs: ["Confidence describes how well evidence supports the conclusion; severity describes the consequence in context. Coverage describes which boundaries were exercised. List confirmed findings, observations, and unavailable checks clearly so quantity does not substitute for assessment quality."], checklist: ["Explain the rating and prerequisites instead of displaying an unexplained label.", "State when timing or a format match remains inconclusive.", "Record missing credentials, blocked requests, and excluded actions."] },
      { title: "Make repair and retest actionable", paragraphs: ["Name the affected permission or data-handling boundary and the behavior the fix must enforce. A retest entry should connect to the original finding and explain what was rerun. Keep report versions so teams can distinguish an initial issue from a verified remediation or an accepted risk."], source: 0 },
    ],
    limitations: "A report is not a warranty that every vulnerability was found. Passing selected checks only covers the tested conditions. Customer data and raw secrets need a protected evidence process rather than inclusion in broadly shared documents.",
    faqs: [
      { question: "Does an empty report mean the application is secure?", answer: "It means no findings were reported within that assessment. Review coverage, roles, exclusions, failed checks, and test depth before drawing a broader conclusion." },
      { question: "What makes a finding reproducible?", answer: "A reader needs the tested environment, relevant role and fixture, request or steps, expected behavior, observed outcome, and conditions under which the result was repeated." },
      { question: "Should every scanner observation have a high severity?", answer: "No. Rate the established impact and prerequisites. Informational configuration observations and inconclusive signals should be distinguished from verified permission or data failures." },
    ],
    sources: [{ title: "OWASP Web Security Testing Guide v4.2: Reporting", url: "https://wstg.owasp.org/v4.2/5-Reporting/" }],
    related: ["remediation-retesting", "automated-vs-manual-testing", "pentest-scope-authorization"],
  },
  {
    slug: "remediation-retesting",
    title: "Remediation and retesting: verify the security behavior",
    description: "Plan security retests around the original evidence, negative and positive controls, deployment identity, adjacent routes, and clear closure outcomes.",
    category: "Testing workflow",
    answer: "A security retest verifies that the deployed change prevents the original unauthorized behavior while preserving legitimate use. Recreate the original conditions with safe fixtures, verify the relevant boundary, and record exactly which issue and deployment the result covers.",
    updated: UPDATED,
    sections: [
      { title: "Turn the finding into an acceptance rule", paragraphs: ["Translate the report into a testable statement: account A cannot download account B's private attachment, while B can still download it. Agree the repair owner and evidence needed for closure. Vulnerability management includes remediation as a continuing process rather than a one-time list of alerts."], source: 0 },
      { title: "Confirm the deployed change", paragraphs: ["Record the deployment or release identifier and target environment. A patched branch or successful build does not establish that the customer-facing route runs that code. Check configuration, cached assets, and gateway behavior when those formed part of the original issue."], checklist: ["Use the same route and relevant roles as the original finding.", "Refresh or rebuild fixtures without changing the permission rule.", "Record when the retest occurred and what version it exercised."] },
      { title: "Run negative and positive controls", paragraphs: ["Verify the forbidden action now fails and that the intended action still succeeds. Inspect persisted state for mutations rather than relying on an error screen. If a gateway blocks the request before the repaired code is reached, describe that observation without claiming the root cause was eliminated."], checklist: ["Retest an adjacent route that shares the repaired helper.", "Include a legitimate request to catch blanket-denial regressions.", "Preserve redacted evidence for both outcomes."] },
      { title: "Choose an accurate closure status", paragraphs: ["Use outcomes such as verified fixed, still reproducible, partially mitigated, or not retested with a reason. When access is unavailable, record the limitation. A focused retest establishes a result for the selected finding; broader assessment requires its own scope and coverage."] },
    ],
    limitations: "A focused retest is not a fresh assessment of the whole application. Staging success may not match production configuration. An unavailable endpoint, missing fixture, or unrelated protective block can make a result inconclusive rather than fixed.",
    faqs: [
      { question: "Does a merged fix mean the vulnerability is closed?", answer: "It establishes a code change was accepted. Verify the deployed behavior under the relevant conditions before describing the issue as retested and fixed." },
      { question: "Why include a valid request in a retest?", answer: "A repair that rejects every caller can remove the demonstrated failure by breaking the feature. A positive control verifies that authorized use still works." },
      { question: "Can a retest confirm the entire application is secure?", answer: "No. It checks specified findings and related regression paths. Report its scope separately from any broader assessment." },
    ],
    sources: [{ title: "OWASP Vulnerability Management Guide", url: "https://owasp.org/projects/vulnerability-management-guide?tab=main" }],
    related: ["security-testing-report", "access-control-testing", "business-logic-testing"],
  },
  {
    slug: "automated-vs-manual-testing",
    title: "Automated vs manual security testing: choose useful coverage",
    description: "Compare automated scanning, manual assessment, source review, and regression testing by the evidence and application context each can provide.",
    category: "Testing workflow",
    answer: "Automated and manual security testing serve different assessment needs. Automation supports repeatable checks across many routes; manual analysis adds application context, workflow reasoning, and targeted validation. Choose a combination around the risks and evidence your application needs.",
    updated: UPDATED,
    sections: [
      { title: "Choose by assessment objective", paragraphs: ["An external configuration baseline, a two-tenant permission review, and a checkout workflow assessment need different inputs. Name the decision the assessment must support before comparing tools. A large check count says little about whether the relevant role, data, or state was exercised."], checklist: ["List critical data and irreversible product actions.", "Identify which test identities and fixtures are available.", "Record whether source and configuration review are in scope."] },
      { title: "Use automation for repeatable checks", paragraphs: ["Dynamic scanning, code analysis, and dependency checks inspect different aspects of a system. Repeatable tooling can supply breadth and baseline regression signals, while human validation helps interpret findings in application context. No single technique covers every security property."], source: 0 },
      { title: "Reserve context-rich paths for targeted review", paragraphs: ["A generic tool may not know that a manager cannot approve their own request or that a tenant's export must exclude another workspace. Provide those rules and fixtures to the assessment. Manual and semi-automated work can then test specific forbidden outcomes rather than guessing policy from page labels."], checklist: ["Review account recovery, privileged actions, and tenant boundaries.", "Use actual workflow states instead of only anonymous crawling.", "Validate candidates before assigning business impact."] },
      { title: "Compare providers with evidence", paragraphs: ["Ask what is included, what is excluded, which roles are exercised, and how findings are verified. Request a redacted sample report and a coverage explanation. For repeat assessments, check whether previous findings and new application routes are handled explicitly instead of assuming unchanged coverage."] },
    ],
    limitations: "Manual work varies with scope, available context, and assessor expertise; automation varies with configuration and target reachability. Neither label proves quality. A point-in-time result does not guarantee future releases preserve the same behavior.",
    faqs: [
      { question: "Can automated scanning replace every manual test?", answer: "It cannot establish every application-specific business rule or permission boundary by itself. Assess the required context and evidence, then add targeted review where necessary." },
      { question: "Is manual testing always more useful?", answer: "Use the method that fits the objective. Automation can make repeatable coverage practical, while focused manual work can investigate context-rich paths and validate results." },
      { question: "What should I ask before buying a security assessment?", answer: "Ask for its scope, roles, methods, exclusions, evidence standards, sample report, and retest process. Compare the covered decisions rather than promises or finding counts." },
    ],
    sources: [{ title: "OWASP Web Security Testing Guide: balanced testing approach", url: "https://wstg.owasp.org/latest/2-Introduction/" }],
    related: ["security-testing-report", "pentest-scope-authorization", "business-logic-testing"],
  },
  {
    slug: "attack-surface-inventory",
    title: "Build an attack surface inventory for security testing",
    description: "Map application routes, identities, data flows, integrations, and exposed assets into an owner-verified inventory with explicit assessment status.",
    category: "Testing workflow",
    answer: "An attack surface inventory maps the places where data or commands enter and leave a system, the valuable resources they reach, and the controls around them. Combine owner-provided architecture with observed application behavior, then track what has actually been assessed.",
    updated: UPDATED,
    sections: [
      { title: "Map functions and boundaries", paragraphs: ["Include browser routes, API operations, uploads, exports, administrative interfaces, and integrations. Associate each with its owner, environment, user roles, and data sensitivity. Discovery is useful for locating assessment work; an exposed route is not automatically a vulnerability."], source: 0 },
      { title: "Walk real application journeys", paragraphs: ["A crawl can miss features that require sign-in, an existing record, or a completed workflow step. Walk through owned test-account journeys and compare the observed requests with the route inventory. Follow a created record through list, detail, export, and deletion paths."], checklist: ["Use the owner's API specification and architecture diagrams.", "Include background jobs and generated download resources.", "Mark unreachable and credential-dependent routes explicitly."] },
      { title: "Prioritize meaningful changes", paragraphs: ["A new upload processor creates a different boundary from another static page. Add a change note describing the new data path and controls it needs. This helps a release assessment focus on the risk introduced rather than repeating every old check without context."], source: 0, checklist: ["Flag new privileged roles and new third-party integrations.", "Identify public assets that may contain internal configuration.", "Review obsolete APIs and forgotten deployment environments."] },
      { title: "Keep assessment status separate from discovery", paragraphs: ["For each relevant boundary, record assessed, excluded, unavailable, or pending, with a date and reason. A route count measures inventory size, not security assurance. Use that ledger to request missing fixtures and plan targeted follow-up after the release."] },
    ],
    limitations: "An inventory can be incomplete because of missing roles, undisclosed services, inaccessible environments, or runtime conditions. Domain discovery cannot establish ownership or authorization. The inventory supports testing but does not itself validate vulnerabilities.",
    faqs: [
      { question: "Does discovering an endpoint mean it was tested?", answer: "No. Discovery records its presence. Assessment needs relevant requests, roles, controls, and results, or a visible reason the check was unavailable." },
      { question: "Is the attack surface only public URLs?", answer: "No. It also includes inputs, outputs, protected data paths, roles, and integrations within the agreed system boundary. Public URLs are one useful inventory layer." },
      { question: "How should an inventory change after a release?", answer: "Record added and removed data paths, roles, integrations, and controls. Use the change to decide which assessments and regression cases need updating." },
    ],
    sources: [{ title: "OWASP Attack Surface Analysis Cheat Sheet", url: cheatSheet("Attack_Surface_Analysis") }],
    related: ["openapi-security-testing", "pentest-scope-authorization", "exposed-secrets"],
  },
];

export const SECURITY_GUIDE_CATEGORIES: SecurityGuideCategory[] = ["API security", "Web security", "Identity and access", "Testing workflow"];

export function guidePath(slug: string): string {
  return `/guides/${slug}`;
}

export function getSecurityGuide(slug: string): SecurityGuide | undefined {
  return SECURITY_GUIDES.find((guide) => guide.slug === slug);
}
